# **2. Introduction to PyTorch Tensors**

In [ ]:
import torch
import math

# Creating Tensor

torch.empty() 함수는 메모리 공간만 할당하고 초기화는 하지 않음 그래서 무작위 값이 출력된 것 처럼 보임

텐서의 차원과 용어
- 1차원 텐서는 일반적으로 벡터라고 부름
- 2차원 텐서는 행렬이라고 부름
- 3차원 이상은 그냥 텐서라고 부름

In [ ]:
x = torch.empty(3, 4)
print(type(x))
print(x)

<class 'torch.Tensor'>
tensor([[-4.7800e-21,  4.4459e-41, -1.5624e-22,  4.4459e-41],
        [-4.7798e-21,  4.4459e-41, -1.4842e-09,  4.4458e-41],
        [-4.7800e-21,  4.4459e-41,  1.3639e-38,  0.0000e+00]])


In [ ]:
zeros = torch.zeros(2, 3)
print(zeros)

ones = torch.ones(2, 3)
print(ones)

torch.manual_seed(1729)
random = torch.rand(2, 3)
print(random)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])


# Random Tensors and Seeding

In [ ]:
torch.manual_seed(1729)
random1 = torch.rand(2, 3)
print(random1)

random2 = torch.rand(2, 3)
print(random2)

torch.manual_seed(1729)
random3 = torch.rand(2, 3)
print(random3)

random4 = torch.rand(2, 3)
print(random4)

tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])
tensor([[0.2332, 0.4047, 0.2162],
        [0.9927, 0.4128, 0.5938]])
tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])
tensor([[0.2332, 0.4047, 0.2162],
        [0.9927, 0.4128, 0.5938]])


# Tensor Shapes

두개 이상의 텐서에서 연산을 수행할 때 shape이 같아야됨

In [ ]:
x = torch.empty(2, 2, 3)
print(x.shape)
print(x)

empty_like_x = torch.empty_like(x)
print(empty_like_x.shape)
print(empty_like_x)

zeros_like_x = torch.zeros_like(x)
print(zeros_like_x.shape)
print(zeros_like_x)

ones_like_x = torch.ones_like(x)
print(ones_like_x.shape)
print(ones_like_x)

rand_like_x = torch.rand_like(x)
print(rand_like_x.shape)
print(rand_like_x)

torch.Size([2, 2, 3])
tensor([[[ 1.2744e-12,  0.0000e+00, -1.4569e-09],
         [ 4.4458e-41,  0.0000e+00,  0.0000e+00]],

        [[ 0.0000e+00,  0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00]]])
torch.Size([2, 2, 3])
tensor([[[-1.0902e-20,  4.4459e-41,  1.0335e-11],
         [ 0.0000e+00,  1.0444e-11,  0.0000e+00]],

        [[ 0.0000e+00,  0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  1.0465e-11,  0.0000e+00]]])
torch.Size([2, 2, 3])
tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])
torch.Size([2, 2, 3])
tensor([[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]])
torch.Size([2, 2, 3])
tensor([[[0.6128, 0.1519, 0.0453],
         [0.5035, 0.9978, 0.3884]],

        [[0.6929, 0.1703, 0.1384],
         [0.4759, 0.7481, 0.0361]]])


리스트나 튜플을 기반으로 텐서를 생성함

torch.tensor()는 넘겨준 데이터의 복사본을 생성 (원본을 공유하는 형태가 아님)

In [ ]:
some_constants = torch.tensor([[2.32154, 5.21432], [1.234768, 0.01233]])
print(some_constants)

some_integers = torch.tensor((2, 3, 5, 7, 11, 13 ,17, 19))
print(some_integers)

more_integers = torch.tensor(((2, 4, 6), [3, 5, 9]))
print(more_integers)

tensor([[2.3215, 5.2143],
        [1.2348, 0.0123]])
tensor([ 2,  3,  5,  7, 11, 13, 17, 19])
tensor([[2, 4, 6],
        [3, 5, 9]])


# Tensor Data Types

In [ ]:
a = torch.ones((2, 3), dtype = torch.int16)
print(a)

b = torch.rand((2, 3), dtype = torch.float64) * 20
print(b)

c = b.to(torch.int32)
print(c)

tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int16)
tensor([[ 0.9956,  1.4148,  5.8364],
        [11.2406, 11.2083, 11.6692]], dtype=torch.float64)
tensor([[ 0,  1,  5],
        [11, 11, 11]], dtype=torch.int32)


# Math & Logic with PyTorch Tensors

In [ ]:
ones = torch.zeros(2, 2) + 1
twos = torch.ones(2, 2) * 2
threes = (torch.ones(2, 2) * 7 - 1) / 2
fours = twos ** 2
sqrt2s = twos ** 0.5

print(ones)
print(twos)
print(threes)
print(fours)
print(sqrt2s)

tensor([[1., 1.],
        [1., 1.]])
tensor([[2., 2.],
        [2., 2.]])
tensor([[3., 3.],
        [3., 3.]])
tensor([[4., 4.],
        [4., 4.]])
tensor([[1.4142, 1.4142],
        [1.4142, 1.4142]])


shape이 다르면 애초에 연산 자체가 안됨

In [ ]:
powers2 = twos ** torch.tensor([[1, 2], [3, 4]])
print(powers2)

fives = ones + fours
print(fives)

dozens = threes * fours
print(dozens)

tensor([[ 2.,  4.],
        [ 8., 16.]])
tensor([[5., 5.],
        [5., 5.]])
tensor([[12., 12.],
        [12., 12.]])


# In Breif: Tensor Broadcasting

브로드캐스팅 규칙
1. 모든 텐서는 최소한 하나의 차원을 가져야 함 (빈 텐서 안됨)
2. 오른쪽 부터 차원을 비교하면서 아래중 하나만 만족하면 됨
- 두 차원이 같다
- 둘중 하나가 1이다
- 한 텐서에는 그 차원이 없다

a = torch.ones(4, 3, 2)

b = a * torch.rand(4, 3)

c = a * torch.rand(2, 3)

d = a * torch.rand((0,))

이것들 싹다 안되는거

rand 는 2 x 4
doubled 는 1 x 4
인데 doubled 가 브로드캐스팅 되서 2 x 4로 계산됨

In [ ]:
rand = torch.rand(2, 4)
doubled = rand * (torch.ones(1, 4) * 2)

print(rand)
print(doubled)

tensor([[0.6146, 0.5999, 0.5013, 0.9397],
        [0.8656, 0.5207, 0.6865, 0.3614]])
tensor([[1.2291, 1.1998, 1.0026, 1.8793],
        [1.7312, 1.0413, 1.3730, 0.7228]])


이것들도 싹다 브로드 캐스팅 되서 연산 진행되는거

In [ ]:
a = torch.ones(4, 3, 2)

b = a * torch.rand(3, 2)
print(b)

c = a * torch.rand(3, 1)
print(c)

d = a * torch.rand(1, 2)
print(d)

tensor([[[0.6493, 0.2633],
         [0.4762, 0.0548],
         [0.2024, 0.5731]],

        [[0.6493, 0.2633],
         [0.4762, 0.0548],
         [0.2024, 0.5731]],

        [[0.6493, 0.2633],
         [0.4762, 0.0548],
         [0.2024, 0.5731]],

        [[0.6493, 0.2633],
         [0.4762, 0.0548],
         [0.2024, 0.5731]]])
tensor([[[0.7191, 0.7191],
         [0.4067, 0.4067],
         [0.7301, 0.7301]],

        [[0.7191, 0.7191],
         [0.4067, 0.4067],
         [0.7301, 0.7301]],

        [[0.7191, 0.7191],
         [0.4067, 0.4067],
         [0.7301, 0.7301]],

        [[0.7191, 0.7191],
         [0.4067, 0.4067],
         [0.7301, 0.7301]]])
tensor([[[0.6276, 0.7357],
         [0.6276, 0.7357],
         [0.6276, 0.7357]],

        [[0.6276, 0.7357],
         [0.6276, 0.7357],
         [0.6276, 0.7357]],

        [[0.6276, 0.7357],
         [0.6276, 0.7357],
         [0.6276, 0.7357]],

        [[0.6276, 0.7357],
         [0.6276, 0.7357],
         [0.6276, 0.7357]]])


In [ ]:
a = torch.rand(2, 4) * 2 - 1
print('Common functions:')
print(torch.abs(a)) # 절댓값
print(torch.ceil(a)) # 올림
print(torch.floor(a)) # 내림
print(torch.clamp(a, -0.5, 0.5)) # 값 제한 최소가 -0.5 최대가 0.5

angles = torch.tensor([0, math.pi / 4, math.pi / 2, 3 * math.pi / 4])
sines = torch.sin(angles) # sin 값 구하기
inverses = torch.asin(sines) # sin 역함수
print('\nSine and arcsine:')
print(angles)
print(sines)
print(inverses)

print('\nBitwise XOR:')
b = torch.tensor([1, 5, 11])
c = torch.tensor([2, 7, 10])
print(torch.bitwise_xor(b,c)) # 비트 연산중 XOR 연산

print('\nBroadcasted, element-wise equality comparison:')
d = torch.tensor([[1., 2.], [3., 4.]])
e = torch.ones(1, 2)
print(torch.eq(d, e)) # 동일한 위치의 값이 같은가 보고 bool 텐서 반환

print('\nReduction ops:')
print(torch.max(d)) # 최대값
print(torch.max(d).item()) # .item() 으로 스칼라 추출
print(torch.mean(d)) # 평균
print(torch.std(d)) # 표준편차
print(torch.prod(d)) # 원소 곱
print(torch.unique(torch.tensor([1, 2, 1, 2, 1, 2]))) # 중복 무시하고 고유한 것만 추출

v1 = torch.tensor([1., 0., 0.]) # unit vector
v2 = torch.tensor([0., 1., 0.]) # unit vector
m1 = torch.rand(2, 2)
m2 = torch.tensor([[3., 0.], [0., 3.]])

print('\nVectors & Matrices:')
print(torch.linalg.cross(v2, v1)) # v1 과 v2 외적
print(m1)
m3 = torch.linalg.matmul(m1, m2)
print(m3)
print(torch.linalg.svd(m3))

Common functions:
tensor([[0.0476, 0.4484, 0.8447, 0.1992],
        [0.9755, 0.9295, 0.8190, 0.1029]])
tensor([[-0., 1., -0., -0.],
        [1., -0., -0., -0.]])
tensor([[-1.,  0., -1., -1.],
        [ 0., -1., -1., -1.]])
tensor([[-0.0476,  0.4484, -0.5000, -0.1992],
        [ 0.5000, -0.5000, -0.5000, -0.1029]])

Sine and arcsine:
tensor([0.0000, 0.7854, 1.5708, 2.3562])
tensor([0.0000, 0.7071, 1.0000, 0.7071])
tensor([0.0000, 0.7854, 1.5708, 0.7854])

Bitwise XOR:
tensor([3, 2, 1])

Broadcasted, element-wise equality comparison:
tensor([[ True, False],
        [False, False]])

Reduction ops:
tensor(4.)
4.0
tensor(2.5000)
tensor(1.2910)
tensor(24.)
tensor([1, 2])

Vectors & Matrices:
tensor([ 0.,  0., -1.])
tensor([[0.8740, 0.2526],
        [0.6923, 0.7545]])
tensor([[2.6220, 0.7577],
        [2.0769, 2.2636]])
torch.return_types.linalg_svd(
U=tensor([[-0.6567, -0.7542],
        [-0.7542,  0.6567]]),
S=tensor([3.9588, 1.1017]),
Vh=tensor([[-0.8306, -0.5569],
        [-0.5569,  0.830

# Altering Tensor in Place

메모리 공간을 새로 할당하지 않고 직접 수정 해보자(inplace하게)


In [ ]:
a = torch.tensor([0, math.pi / 4, math.pi / 2, 3 * math.pi / 4])
print('a:')
print(a)
print(torch.sin(a)) # torch.sin(a)는 a의 sin 값을 계산해서 새 텐서를 생성함
print(a) # 그래서 a 자체가 바뀌지 않은걸 확인 가능

b = torch.tensor([0, math.pi / 4, math.pi / 2, 3 * math.pi / 4])
print('\nb:')
print(b)
print(torch.sin_(b)) # _ 를 붙이면 inplace하게 덮어 씌어버림
print(b) # 그래서 b 값이 변경된 걸 확인할 수 있음

a:
tensor([0.0000, 0.7854, 1.5708, 2.3562])
tensor([0.0000, 0.7071, 1.0000, 0.7071])
tensor([0.0000, 0.7854, 1.5708, 2.3562])

b:
tensor([0.0000, 0.7854, 1.5708, 2.3562])
tensor([0.0000, 0.7071, 1.0000, 0.7071])
tensor([0.0000, 0.7071, 1.0000, 0.7071])


In [ ]:
a = torch.ones(2, 2)
b = torch.rand(2, 2)

print('Before:')
print(a)
print(b)
print('\nAfter adding:')
print(a.add_(b))
print(a)
print(b)
print('\nAfter multiplying')
print(b.mul_(b)) # 더하고 곱하는 산술연산 또한 _를 붙여 inplace하게 수정이 됨
print(b)

Before:
tensor([[1., 1.],
        [1., 1.]])
tensor([[0.9970, 0.1552],
        [0.9899, 0.8562]])

After adding:
tensor([[1.9970, 1.1552],
        [1.9899, 1.8562]])
tensor([[1.9970, 1.1552],
        [1.9899, 1.8562]])
tensor([[0.9970, 0.1552],
        [0.9899, 0.8562]])

After multiplying
tensor([[0.9941, 0.0241],
        [0.9799, 0.7331]])
tensor([[0.9941, 0.0241],
        [0.9799, 0.7331]])


In [ ]:
a = torch.rand(2, 2)
b = torch.rand(2, 2)
c = torch.zeros(2, 2) # 미리 zoro tensor를 생성해둠
old_id = id(c) # c 의 메모리 주소 저장

print(c)
d = torch.matmul(a, b, out = c) # 연산결과를 미리 만들어둔 c 에 저장함
print(c)

# assert 는 뒤에 오는 조건이 반드시 참이길 기대함 false면 중단
assert c is d # c와 d가 같은 객체인가 확인
assert id(c) == old_id # c 의 메모리 주소가 변경되진 않았는가?

torch.rand(2, 2, out = c) # c 에 랜덤한 텐서 넣음
print(c)
assert id(c) == old_id # 같은 메모리 주소인가?

tensor([[0., 0.],
        [0., 0.]])
tensor([[0.4302, 0.4372],
        [1.0694, 0.7633]])
tensor([[0.0543, 0.3826],
        [0.4481, 0.1471]])


# Copying Tensord

In [ ]:
a = torch.ones(2,2)
b = a # 이건 그냥 에일리어싱인듯 별칭만 생

a[0][1] = 561
print(b) # 텐서는 복사가 안됨 b도 함께 바뀌어 버림

tensor([[  1., 561.],
        [  1.,   1.]])


In [ ]:
a = torch.ones(2,2)
b = a.clone() # 클론으로 복사해야 복사본이 생성됨

assert b is not a # 둘이 다른 객체면 중지
print(torch.eq(a, b))

a[0][1] = 561
print(b)

tensor([[True, True],
        [True, True]])
tensor([[1., 1.],
        [1., 1.]])


In [ ]:
a = torch.rand(2, 2, requires_grad = True) # requires_grad = True 상태의 텐서
print(a)

b = a.clone() # 를 clone() 하면 autograd 정보도 복사해버림
print(b)

c = a.detach().clone() # autograd 추적을 끄고 복사하고 싶으면 detach() 해줘야
print(c)

print(a)

tensor([[0.2139, 0.7135],
        [0.3945, 0.0210]], requires_grad=True)
tensor([[0.2139, 0.7135],
        [0.3945, 0.0210]], grad_fn=<CloneBackward0>)
tensor([[0.2139, 0.7135],
        [0.3945, 0.0210]])
tensor([[0.2139, 0.7135],
        [0.3945, 0.0210]], requires_grad=True)


# Moving to Accelerator

엑셀레이터 사용법

In [ ]:
if torch.accelerator.is_available(): # 현재 accelerator가 있는지 확인
  print('We have an accelerator')
else:
  print('sorry, CPU only')

sorry, CPU only


In [ ]:
if torch.accelerator.is_available():
  gpu_rand = torch.rand(2, 2, device = torch.accelrator.current_accelerator())
  print(gpu_rand)
else:
  print('sorry, CPU only')

sorry, CPU only


In [ ]:
my_device = torch.accelerator.current_accelerator() if torch.accelerator.is_available() else torch.device('cpu')
print('device : {}'.format(my_device))

x = torch.rand(2, 2, device = my_device)
print(x)

device : cpu
tensor([[0.8086, 0.3561],
        [0.5689, 0.8520]])


In [ ]:
y = torch.rand(2, 2)
y = y.to(my_device)

In [ ]:
x = torch.rand(2, 2)
y = torch.rand(2, 2, device='cuda')
z = x + y # 에러 발생하는게 맞음 장치가 다르니까

RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx

# Manipulating Tensor Shapes

In [ ]:
a = torch.rand(3, 226, 226)
b = a.unsqueeze(0) # unsqueeze(dim)은 차원을 추가하는 거임

print(a.shape)
print(b.shape)

torch.Size([3, 226, 226])
torch.Size([1, 3, 226, 226])


In [ ]:
c = torch.rand(1,1,1,1,1)
print(c)

tensor([[[[[0.9840]]]]])


In [ ]:
a = torch.rand(1, 20)
print(a.shape)
print(a)

b = a.squeeze(0) # squeeze(dim) 은 차원이 1인 경우 제거하는 역할임
print(b.shape)
print(b) # 대괄호 하나가 사라짐 출력에서

c = torch.rand(2, 2)
print(c.shape)

d = c.squeeze(0) # c의 차원이 2니까 제거가 안되는거임
print(d.shape)

torch.Size([1, 20])
tensor([[0.9703, 0.7680, 0.7405, 0.4078, 0.2471, 0.2228, 0.9214, 0.8073, 0.0367,
         0.8370, 0.8346, 0.1887, 0.0828, 0.3268, 0.4444, 0.4285, 0.2654, 0.7644,
         0.3006, 0.6279]])
torch.Size([20])
tensor([0.9703, 0.7680, 0.7405, 0.4078, 0.2471, 0.2228, 0.9214, 0.8073, 0.0367,
        0.8370, 0.8346, 0.1887, 0.0828, 0.3268, 0.4444, 0.4285, 0.2654, 0.7644,
        0.3006, 0.6279])
torch.Size([2, 2])
torch.Size([2, 2])


In [ ]:
a = torch.ones(4, 3, 2)

c = a * torch.rand(3, 1) # 브로드 캐스팅 되서 연됨
print(c)

tensor([[[0.1216, 0.1216],
         [0.0670, 0.0670],
         [0.4221, 0.4221]],

        [[0.1216, 0.1216],
         [0.0670, 0.0670],
         [0.4221, 0.4221]],

        [[0.1216, 0.1216],
         [0.0670, 0.0670],
         [0.4221, 0.4221]],

        [[0.1216, 0.1216],
         [0.0670, 0.0670],
         [0.4221, 0.4221]]])


In [ ]:
a = torch.ones(4,3,2)
b = torch.rand(3)
c = b.unsqueeze(1) # 브로드캐스팅 되라고 unsqueeze 해주는거임
print(c.shape)
print(a * c)

torch.Size([3, 1])
tensor([[[0.2508, 0.2508],
         [0.0419, 0.0419],
         [0.7431, 0.7431]],

        [[0.2508, 0.2508],
         [0.0419, 0.0419],
         [0.7431, 0.7431]],

        [[0.2508, 0.2508],
         [0.0419, 0.0419],
         [0.7431, 0.7431]],

        [[0.2508, 0.2508],
         [0.0419, 0.0419],
         [0.7431, 0.7431]]])


In [ ]:
batch_me = torch.rand(3, 266, 266)
print(batch_me.shape)
batch_me.unsqueeze_(0) # _ 는 inplace 연산이라는거임 동일하게
print(batch_me.shape)

torch.Size([3, 266, 266])
torch.Size([1, 3, 266, 266])


reshape() 은 내부적으로 view를 반환함 (원래 메모리 참조)

값 복사가 아닌 형태만 바뀐 별도의 객체를 얻을려면 clone()해야함

그리고 아래의 경우 튜플로 shape을 지정해야 해서 (,) 해준거임



In [ ]:
# fully connected 에서 이러한 reshape 을 할거임
output3d = torch.rand(6, 20 , 20)
print(output3d.shape)

input1d = output3d.reshape(6 * 20 * 20)
print(input1d.shape)

print(torch.reshape(output3d, (6* 20 * 20,)).shape)

torch.Size([6, 20, 20])
torch.Size([2400])
torch.Size([2400])


# Numpy Bridge

파이토치의 브로드캐스팅이 넘파이와 호환됨

넘파이의 array와 파이토치의 tensor 간의 전환을 볼거임

In [ ]:
import numpy as np

numpy_array = np.ones((2,3))
print(numpy_array)

# torch.from_numpy()는 numpy 배열로부터 동일한 형태와 값을 가지는 파이토치 tensor를 생성
pytorch_tensor = torch.from_numpy(numpy_array)
print(pytorch_tensor)

[[1. 1. 1.]
 [1. 1. 1.]]
tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [ ]:
pytorch_rand = torch.rand(2,3)
print(pytorch_rand)

# pytorch_rand.numpy() tensor가 array로 변환되는데 이때 동일한 메모리를 공유함
numpy_rand = pytorch_rand.numpy()
print(numpy_rand)

tensor([[0.3286, 0.4498, 0.8829],
        [0.2496, 0.1804, 0.7484]])
[[0.32859033 0.44979417 0.882865  ]
 [0.24956638 0.18040317 0.7483587 ]]


In [ ]:
# 넘파이 배열의 변경이 텐서에도 영향
# 텐서의 변경이 넘파이 배열에도 영향
numpy_array[1,1] = 23
print(pytorch_tensor)

pytorch_rand[1,1] = 17
print(numpy_rand)

tensor([[ 1.,  1.,  1.],
        [ 1., 23.,  1.]], dtype=torch.float64)
[[ 0.32859033  0.44979417  0.882865  ]
 [ 0.24956638 17.          0.7483587 ]]
