# **2. Tensors**

텐서는 배열, 행렬과 유사한 자료구조

파이토치에선 모델의 입력, 출력, 파라미터를 표현할때 텐서를 사용함

텐서는 numpy의 ndarray와 비슷하지만 차이점 존재
1. 텐서는 GPU와 같은 가속기에서 실행 가능
2. 텐서와 Numpy 배열은 종종 같은 메모리 공간을 공유할 수 있어 복사 없이 변환 가능
3. 텐서는 자동 미분(autograd)에 최적화 되어있음)

In [ ]:
import torch
import numpy as np

# Inirializing a Tensor

데이터에서 직접 초기화 하는거 데이터 유형은 자동 추론

In [ ]:
data = [[1,2],[3,4]]
x_data = torch.tensor(data)

넘파이 배열에서 텐서 생성 가능(반대도 가능)

In [ ]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

In [ ]:
# ones_like 는 shape과 dtype을 기존 텐서로부터 복사
x_ones = torch.ones_like(x_data)
print(f"Ones Tensor: \n {x_ones} \n")

# rand_like 는 shape은 유지하지만 dtype만 바꿔서 랜덤 텐서 생성
x_rand = torch.rand_like(x_data, dtype=torch.float)
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.8439, 0.5319],
        [0.9893, 0.1521]]) 



In [ ]:
shape = (2,3,)
rand_tensor = torch.rand(shape) # 랜덤 값으로 텐서 생성
ones_tensor = torch.ones(shape) # 1로 텐서 생성
zeros_tensor = torch.zeros(shape) # 0으로 텐서 생성

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.0518, 0.5438, 0.6260],
        [0.5618, 0.7129, 0.9396]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


# Attributes of a Tensor

shape, datatype, 저장되는 device 설명임

In [ ]:
tensor = torch.rand(3,4)

print(f"shape of tensor {tensor.shape}")
print(f"datatype of tensor {tensor.dtype}")
print(f"device tensor is stored on {tensor.device}")

shape of tensor torch.Size([3, 4])
datatype of tensor torch.float32
device tensor is stored on cpu


# Operations on Tensors

텐서 연산은 산술, 선형 대수, 행렬 조작, 샘플링등이 존재

기본적으로 텐서는 CPU에서 생성되는데 .to 메소드를 통해 GPU 같은 가속기로 명시적으로 이동시켜야됨

In [ ]:
if torch.accelerator.is_available():
  tensor = tensor.to(torch.accelerator.current_accelerator())

인덱싱과 슬라이싱


In [ ]:
tensor = torch.ones(4, 4)
print(f"First row: {tensor[0]}")
print(f"First column: {tensor[:, 0]}")
print(f"Last column: {tensor[..., -1]}")
tensor[:,1] = 0 # 1번째 열을 0으로 채움
print(tensor)

First row: tensor([1., 1., 1., 1.])
First column: tensor([1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


텐서 결합으로 시퀀스 연결

In [ ]:
t1 = torch.cat([tensor, tensor, tensor], dim = 1)
print(t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


In [ ]:
t2 = torch.stack([tensor, tensor, tensor], dim = 1)
print(t2)

tensor([[[1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.]],

        [[1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.]],

        [[1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.]],

        [[1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.]]])


산술 연산

out =

하는건 미리 저장할 버퍼를 만들어 놓고 거기다 값을 넣을려고 하는 행동인거 같음

In [ ]:
# 행렬 곱 연산으로 y1 = y2 같은 결과값임
# rand_like 는 shape은 유지하지만 dtype만 바꿔서 랜덤 텐서 생성
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)
y3 = torch.rand_like(y1)

torch.matmul(tensor, tensor.T, out=y3)

tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])

In [ ]:
# 원소별 곱연산임 이건 z1 = z2 같은 결과
z1 = tensor * tensor
z2 = tensor.mul(tensor)
z3 = torch.rand_like(tensor)

torch.mul(tensor, tensor, out=z3)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

In [ ]:
# tensor([[1., 0., 1., 1.],
#        [1., 0., 1., 1.],
#        [1., 0., 1., 1.],
#        [1., 0., 1., 1.]])
agg = tensor.sum() # 모든 원소의 합 즉, 하나의 값만 있는 텐서 형태
agg_item = agg.item() # .item()은 파이썬 숫자로 변경시킴
print(agg_item, type(agg_item)) # 그래서 float으로 변경된거

12.0 <class 'float'>


In-place 연산

접미사 _가 붙으면 inplace연산임 기존값 자체를 변경시켜버림

inplace 연산은 메모리를 절약할 수는 있으나 함수 계산에서 히스토리가 즉시 삭제되서 문제 야기 가능하여 권장 안된다.

In [ ]:
# 각 원소에 5를 더함
print(f"{tensor}\n")
tensor.add_(5)
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


# Birdge with Numpy (넘파이와의 연결성)

In [ ]:
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


In [ ]:
# 텐서에 더했는데 넘파이 배열도 변경됨
t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


In [ ]:
n = np.ones(5)
t = torch.from_numpy(n)

In [ ]:
# 넘파이 배열에 더했는데 텐서도 같이 변경됨
np.add(n, 1, out = n)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]
